#!/bin/sh
#
# curie_pydoc3
#
# Eric Viara, Institut Curie, 29 December 2014
#

if [ $# != 1 ]; then
   echo "usage: $0 PYTHON_MODULE"
   exit 1
fi

file=$1
tmpfile=tmp_${file}

pydoc3 -w $file

cat $file.html | awk '
BEGIN {
  p_cnt = 0;
}
$1 ~ "<p>" {
  if (p_cnt == 1) {
     printf("<!--\n");
     print
  } else if (p_cnt == 2) {
     print
     printf("-->\n");
  } else {
    print
  }
  p_cnt++;
  next
}
{print}
' - | sed -e 's/#f0f0f8/#ffffff/' -e 's/#7799ee/#ff8500/' -e 's/#ee77aa/#ff8500/' -e 's/#ffc8d8/#f3efeb/' -e 's|>/.*/navicell.py<|><|' -e 's|>index<|><|' -e 's|<a href="curie.html">|<a>|' > $tmpfile

mv $tmpfile $file.html
